#!/usr/bin/env python
import os
print ("CREDITOS AL DEVOLEPER")
print ("CREADOR: DrowKid")
print ("DATE: 12/07/2018")
print ("TELEGRAM: https://t.me/drowkid01")
print ("YOUTUBE: https://youtube.com/@drowkid01")
print ("MENSAJE: Nunca dejes de aprender")
print ("")

raw_input("Presiona enter para continuar")
os.system("python2 cc-genpro2.0.py")
